### PR TITLE
README rethink, prepare for renaming (reopened)

### PR DESCRIPTION
**Pull request by h1alexbel**
ref #83 
@l3r8yJ take a look, please

---

### Detailed summary
- Added badges for Maven Central, Javadoc, Hits-of-Code, Lines-of-Code, PDD status, and License
- Updated the motivation section in the README.md file
- Added examples of valid and invalid classes
- Added sections for Parsers, Validators, Controllers, Utility classes, Getters, Objects without state, and Long class names
- Updated the contribution guidelines in the README.md file

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Review by l3r8yJ — APPROVED** [review]

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-01T09:10:04.156416``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ can you trigger it once again?

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
