### PR TITLE
README rethink, prepare for renaming

### PR DESCRIPTION
**Pull request by h1alexbel**
ref #83 

@l3r8yJ take a look, please

---

### Detailed summary
- Added badges for Maven Central, Javadoc, Hits-of-Code, Lines-of-Code, PDD status, and License
- Updated the motivation and added examples for OOPCOP tool
- Added instructions on how to use the tool as a Maven plugin or by running it directly
- Added sections for Mutable Objects, Parsers, Validators, Controllers, Utility classes, Getters, Objects without state, and Long class names
- Updated the contribution guidelines

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-01T08:30:23.072703``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
pdd will be fixed in #84 ,wait for it

**Comment by h1alexbel** [comment]
@l3r8yJ rerun `pdd` please

**Comment by l3r8yJ** [comment]
> @l3r8yJ rerun `pdd` please, it should be fixed

already

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel looks good to me!

**Comment by l3r8yJ** [comment]
@h1alexbel can you reopen this pr?

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by h1alexbel** [comment]
@l3r8yJ what's wrong with this?

**Comment by l3r8yJ** [comment]
@h1alexbel pdd action is starting, it was created before fix

**Comment by h1alexbel** [comment]
check: https://github.com/l3r8yJ/sa-tan/pull/90

**Pull request closed without merging**
